<a href="https://colab.research.google.com/github/sikaiser90/DS10/blob/main/Lab07_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KNN in Scikit Learn

![image.png](attachment:image.png)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 

X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y) 
print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))


[0]
[[0.66666667 0.33333333]]


## IRIS Example

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
X = iris.data
y = iris.target

# x : Sepal Length, Sepal Width, Petal Length and Petal Width
# y : 0 - Setosa, 1 - Versicolour, and 2 - Virginica

# build your own linear regression model using iris data set

# split test & training


In [ ]:
iris_clf = KNeighborsClassifier(n_neighbors=5)
iris_clf.fit(X, y)

KNeighborsClassifier()

In [ ]:
y_pred = iris_clf.predict(X)

In [ ]:
print(y,'\n',y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
error = np.abs(y_pred-y)
error

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
1-5/150

0.9666666666666667

In [ ]:
np.nonzero(error)

(array([ 70,  72,  83, 106, 119], dtype=int64),)

In [ ]:
from sklearn.metrics import accuracy_score

error = accuracy_score(y_pred, y)
print(error)

0.9666666666666667


In [ ]:
iris_clf.score(X,y)

0.9666666666666667

In [ ]:
for feature in data
    if np.randint(1,10) > 7 : 
        X_train.append(data)
        y_train.append(data)
    else :
        X_test.append(data)
        y_test.append(data)
        

SyntaxError: invalid syntax (<ipython-input-107-889de045528a>, line 1)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)

In [ ]:
print (X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(105, 4) (45, 4) (105,) (45,)


In [ ]:
iris_clf_new = KNeighborsClassifier(n_neighbors=5)
iris_clf_new.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y = iris_clf_new.predict(X_test)

In [ ]:
print(y, '\n', y_test)

[0 0 0 1 2 1 0 2 0 0 1 0 0 1 2 1 0 2 1 1 1 2 0 2 2 1 2 0 1 1 0 2 0 1 2 2 2
 1 2 2 2 0 0 0 1] 
 [0 0 0 1 2 1 0 2 0 0 1 0 0 1 2 1 0 2 1 1 1 1 0 2 2 1 2 0 1 1 0 2 0 1 2 2 2
 1 2 2 2 0 0 0 1]


In [ ]:
error = accuracy_score(y, y_test)
print(error)

0.9777777777777777


In [ ]:
error = np.abs(y-y_test)
error

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [ ]:
np.nonzero(error)

(array([0], dtype=int64),)

In [ ]:
from sklearn.datasets import load_iris

X,y = load_iris().data, load_iris().target

In [ ]:
#2) data split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 1/3, random_state = 0 )

In [ ]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(100, 4) (50, 4) (100,) (50,)


In [ ]:
#3) KNN model 만들기
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors = 5)

In [ ]:
#4) KNN model 학습하기
clf.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
#5) KNN 예측하기
y_pred = clf.predict(X_test)

In [ ]:
#6) 성능평가
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_pred, y_test)

In [ ]:
print(acc)

0.98


In [ ]:
# 머신러닝 모델 저장

from joblib import dump, load

dump(clf, 'ourclf.joblib')

['ourclf.joblib']

In [ ]:
# 불러오기

from joblib import dump, load

myclf = load('ourclf.joblib')

In [ ]:
myclf

KNeighborsClassifier()