# SVM in Scikit Learn
![image.png](attachment:image.png)

In [ ]:
from sklearn.svm import SVC

X = [[0, 0], [1, 1]]
y = [0, 1]
clf = SVC(gamma='scale')

clf.fit(X, y) 
print(clf.predict([[2., 2.]]))

[1]


In [ ]:
# get support vectors
print(clf.support_vectors_)

# get indices of support vectors
print(clf.support_)

# get number of support vectors for each class
print(clf.n_support_ )

[[0. 0.]
 [1. 1.]]
[0 1]
[1 1]
[[-1.  1.]]


# IRIS Data example

In [ ]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
X, y = iris.data, iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=1/3)

from sklearn.svm import SVC
clf = SVC(kernel='poly', gamma='scale')

clf.fit(X_train, y_train) 

from sklearn.metrics import accuracy_score
print(accuracy_score(clf.predict(X_test),y_test))




0.96


In [ ]:

clf = SVC(gamma='auto')

clf.fit(X_train, y_train) 

print(accuracy_score(clf.predict(X_test),y_test))

0.98


In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
X, y = iris.data, iris.target

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=1/3)

from sklearn.svm import SVC

clf = SVC()
clf.fit(X_train, y_train) 

from sklearn.metrics import accuracy_score

print(accuracy_score(clf.predict(X_test),y_test))

from sklearn.model_selection import cross_val_score

clf = SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X, y, cv=10)
print(scores)

1.0
[1.         0.93333333 1.         1.         0.86666667 1.
 0.93333333 1.         1.         1.        ]


In [ ]:
from sklearn.datasets import load_wine

wine = load_wine()

print(wine)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [ ]:
wine.data[0]

array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03])

### wine DB를 이용해서 KNN DT SVC 의 앙상블 모델을 짜세요

### 1) data load & split
### 2) 3 ML model
### 3) ensemble model
### 4) predict

In [ ]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score

wine = load_wine()
X, y = wine.data, wine.target

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=1/3)

clf1 = KNeighborsClassifier()
clf2 = DecisionTreeClassifier()
clf3 = SVC()

eclf = VotingClassifier(estimators=[('knn', clf1), ('dt', clf2), ('rf', clf3)], voting='hard')
eclf = eclf.fit(X_train, y_train)

print(accuracy_score(eclf.predict(X_test),y_test))



0.8166666666666667


In [ ]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score

wine = load_wine()
X, y = wine.data, wine.target

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=1/3)

clf1 = KNeighborsClassifier(n_neighbors = 3)
clf2 = DecisionTreeClassifier()
clf3 = SVC()

eclf = VotingClassifier(estimators=[('knn', clf1), ('dt', clf2), ('rf', clf3)], voting='hard')

model = [clf1, clf2, clf3, eclf]

for clf in model : 
    clf.fit(X_train, y_train)
    print(accuracy_score(clf.predict(X_test), y_test))


0.6833333333333333
0.8666666666666667
0.7166666666666667
0.7666666666666667


In [ ]:
clf1 = KNeighborsClassifier()
clf1 = clf1.fit(X_train, y_train)
clf2 = DecisionTreeClassifier()
clf2 = clf2.fit(X_train, y_train)
clf3 = SVC()
clf3 = clf3.fit(X_train, y_train)

In [ ]:
print(accuracy_score(clf1.predict(X_test),y_test))
print(accuracy_score(clf2.predict(X_test),y_test))
print(accuracy_score(clf3.predict(X_test),y_test))

print(clf1.score(X_test,y_test))
print(clf2.score(X_test,y_test))
print(clf3.score(X_test,y_test))


0.6666666666666666
0.85
0.7166666666666667
0.6666666666666666
0.85
0.7166666666666667


In [ ]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score

wine = load_wine()
X, y = wine.data, wine.target

score = []

for _ in range(5) : 
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=1/3)
    clf1 = KNeighborsClassifier(n_neighbors = 3)
    clf1.fit(X_train, y_train)
    score.append(clf1.score(X_test,y_test))

score

[0.75, 0.7, 0.7, 0.7, 0.65]

In [ ]:
from sklearn.model_selection import cross_val_score

clf = SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X, y, cv=5)

print(scores)

[0.88888889 0.94444444 0.97222222 1.         1.        ]
